Martin/coordinator updates
Jibber-Inc/Jibber-iOS pull request #30
Opened 2021-08-26 21:24 UTC by MartinJibber

2021-08-30 19:13 UTC, Benjamindodgson commented on Shared/Coordinator/Coordinator.swift
> +        if self.childCoordinator != nil {
You can use .nil

2021-08-30 19:15 UTC, Benjamindodgson commented on Shared/Coordinator/Router.swift
> +    /// Similar to a push, however the current view controller will removed from the stack once the new one is pushed, effectively making it a swap.
* will be

2021-08-30 19:16 UTC, Benjamindodgson requested changes
2 minor things.

2021-09-01 23:39 UTC, MartinJibber commented on Shared/Coordinator/Router.swift
> +    /// Similar to a push, however the current view controller will removed from the stack once the new one is pushed, effectively making it a swap.
Haha nice catch! This function was written by Ethan technically so it's his original typo.

2021-09-01 23:43 UTC, merged